### ISSUE TITLE
[EPIC] Initial Release ROADMAP

### ISSUE THREAD

**Issue by PedroHLC** [PedroHLC/chaotic-installer-qt#1]
For a complete experience we're mimicking AnarchyLinux's installer, which is split into these parts:
 * [X] ~set_lang~ (Finished in #3)
 * [X] ~set_keys~ (Finished in #4)
 * [x] update_mirrors (Finished in #5)
 * [x] check_connection (Finished in #5)
   * [x] wifi-menu
 * [x] set_locale (Finished in #6)
 * [ ] set_zone (#7)
 * [x] prepare_drives (this will have a completely different approach, discussing at #9 )
 * [x] set_hostname + set_user (#8)
 * [ ] install_options +  add_software (#10)
 * [ ] install_base + configure_system + add_user (completely different approach)
   * [x] Partitioning script review screen (bash script text area with what will be executed during partitioning)
   * [ ] Install script review screen (bash script text area with what will be executed during setup)
   * [ ] Partitioning console view
   * [ ] Install console view
  * [ ] umount, sync, exit and reboot!

Before that:
 * [X] ~Minimal language abstration~ (Solved in #2)

After that:
 * [ ] Add all translations
 * [ ] Allow searching through lists (keymap, mirrors, locales, timezone)
 * [ ] Mirrors automatic operations
 * [ ] Require one mirror server to be selected before continuing
